const BRAND_CONFIG = [
  {
    displayName: "Bank Hapoalim",
    category: "banking",
    aliases: ["bankhapoalim", "hapoalim", "poalim", "בנק הפועלים"],
    officialDomains: ["bankhapoalim.co.il"],
  },
  {
    displayName: "Bank Leumi",
    category: "banking",
    aliases: ["leumi", "bankleumi", "בנק לאומי", "לאומי"],
    officialDomains: ["leumi.co.il"],
  },
  {
    displayName: "Discount Bank",
    category: "banking",
    aliases: ["discount", "discountbank", "בנק דיסקונט", "דיסקונט"],
    officialDomains: ["discountbank.co.il"],
  },
  {
    displayName: "Mizrahi Tefahot",
    category: "banking",
    aliases: ["mizrahi", "tefahot", "mizrahi-tefahot", "מזרחי", "טפחות"],
    officialDomains: ["mizrahi-tefahot.co.il"],
  },
  {
    displayName: "First International Bank",
    category: "banking",
    aliases: ["fibi", "beinleumi", "bankbeinleumi", "הבינלאומי", "בינלאומי"],
    officialDomains: ["fibi.co.il", "otzar.co.il", "u-bank.net"],
  },
  {
    displayName: "Mercantile",
    category: "banking",
    aliases: ["mercantile", "mercantilebank", "מרכנתיל"],
    officialDomains: ["mercantile.co.il"],
  },
  {
    displayName: "Isracard",
    category: "payments",
    aliases: ["isracard", "ישראכרט"],
    officialDomains: ["isracard.co.il"],
  },
  {
    displayName: "MAX",
    category: "payments",
    aliases: ["max", "maxcard", "לאומי קארד"],
    officialDomains: ["max.co.il"],
  },
  {
    displayName: "CAL",
    category: "payments",
    aliases: ["cal", "calonline", "ויזה כאל", "כאל"],
    officialDomains: ["cal-online.co.il"],
  },
  {
    displayName: "Bit",
    category: "payments",
    aliases: ["bit", "bitapp", "ביט"],
    officialDomains: ["bitpay.co.il"],
  },
  {
    displayName: "PayBox",
    category: "payments",
    aliases: ["paybox", "פייבוקס"],
    officialDomains: ["payboxapp.com"],
  },
  {
    displayName: "PayPal",
    category: "payments",
    aliases: ["paypal", "pay pal"],
    officialDomains: ["paypal.com"],
  },
  {
    displayName: "Wise",
    category: "payments",
    aliases: ["wise", "transferwise"],
    officialDomains: ["wise.com"],
  },
  {
    displayName: "Revolut",
    category: "payments",
    aliases: ["revolut"],
    officialDomains: ["revolut.com"],
  },
  {
    displayName: "Visa",
    category: "payments",
    aliases: ["visa"],
    officialDomains: ["visa.com"],
  },
  {
    displayName: "Mastercard",
    category: "payments",
    aliases: ["mastercard", "master card"],
    officialDomains: ["mastercard.com"],
  },
  {
    displayName: "American Express",
    category: "payments",
    aliases: ["amex", "americanexpress", "american express"],
    officialDomains: ["americanexpress.com"],
  },
  {
    displayName: "Google",
    category: "technology",
    aliases: ["google", "gmail", "googlemail"],
    officialDomains: [
      "google.com",
      "google.co.il",
      "googleapis.com",
      "googleusercontent.com",
      "gmail.com",
    ],
  },
  {
    displayName: "Microsoft",
    category: "technology",
    aliases: ["microsoft", "ms", "office", "outlook", "hotmail", "live"],
    officialDomains: [
      "microsoft.com",
      "microsoftonline.com",
      "office.com",
      "outlook.com",
      "live.com",
      "hotmail.com",
    ],
  },
  {
    displayName: "Apple",
    category: "technology",
    aliases: ["apple", "icloud", "itunes"],
    officialDomains: ["apple.com", "icloud.com"],
  },
  {
    displayName: "Amazon",
    category: "shopping",
    aliases: ["amazon", "aws", "prime"],
    officialDomains: ["amazon.com", "amazon.co.uk", "amazon.de", "amazonaws.com"],
  },
  {
    displayName: "eBay",
    category: "shopping",
    aliases: ["ebay"],
    officialDomains: ["ebay.com"],
  },
  {
    displayName: "AliExpress",
    category: "shopping",
    aliases: ["aliexpress", "ali express"],
    officialDomains: ["aliexpress.com"],
  },
  {
    displayName: "Temu",
    category: "shopping",
    aliases: ["temu"],
    officialDomains: ["temu.com"],
  },
  {
    displayName: "SHEIN",
    category: "shopping",
    aliases: ["shein"],
    officialDomains: ["shein.com"],
  },
  {
    displayName: "Wolt",
    category: "shopping",
    aliases: ["wolt"],
    officialDomains: ["wolt.com"],
  },
  {
    displayName: "Gett",
    category: "transport",
    aliases: ["gett", "get taxi"],
    officialDomains: ["gett.com"],
  },
  {
    displayName: "Uber",
    category: "transport",
    aliases: ["uber", "ubereats"],
    officialDomains: ["uber.com"],
  },
  {
    displayName: "Netflix",
    category: "entertainment",
    aliases: ["netflix"],
    officialDomains: ["netflix.com"],
  },
  {
    displayName: "Spotify",
    category: "entertainment",
    aliases: ["spotify"],
    officialDomains: ["spotify.com"],
  },
  {
    displayName: "YouTube",
    category: "entertainment",
    aliases: ["youtube"],
    officialDomains: ["youtube.com", "youtu.be"],
  },
  {
    displayName: "Disney+",
    category: "entertainment",
    aliases: ["disney", "disneyplus", "disney plus"],
    officialDomains: ["disneyplus.com"],
  },
  {
    displayName: "Facebook",
    category: "social",
    aliases: ["facebook", "fb", "meta"],
    officialDomains: ["facebook.com", "fb.com", "meta.com"],
  },
  {
    displayName: "Instagram",
    category: "social",
    aliases: ["instagram", "insta"],
    officialDomains: ["instagram.com"],
  },
  {
    displayName: "WhatsApp",
    category: "social",
    aliases: ["whatsapp", "wa"],
    officialDomains: ["whatsapp.com"],
  },
  {
    displayName: "Telegram",
    category: "social",
    aliases: ["telegram"],
    officialDomains: ["telegram.org"],
  },
  {
    displayName: "TikTok",
    category: "social",
    aliases: ["tiktok", "tik tok"],
    officialDomains: ["tiktok.com"],
  },
  {
    displayName: "LinkedIn",
    category: "social",
    aliases: ["linkedin", "linked in"],
    officialDomains: ["linkedin.com"],
  },
  {
    displayName: "X",
    category: "social",
    aliases: ["twitter", "x", "tweetdeck"],
    officialDomains: ["x.com", "twitter.com"],
  },
  {
    displayName: "GitHub",
    category: "technology",
    aliases: ["github"],
    officialDomains: ["github.com"],
  },
  {
    displayName: "GitLab",
    category: "technology",
    aliases: ["gitlab"],
    officialDomains: ["gitlab.com"],
  },
  {
    displayName: "Dropbox",
    category: "technology",
    aliases: ["dropbox"],
    officialDomains: ["dropbox.com"],
  },
  {
    displayName: "Adobe",
    category: "technology",
    aliases: ["adobe", "acrobat"],
    officialDomains: ["adobe.com"],
  },
  {
    displayName: "Zoom",
    category: "technology",
    aliases: ["zoom"],
    officialDomains: ["zoom.us"],
  },
  {
    displayName: "Slack",
    category: "technology",
    aliases: ["slack"],
    officialDomains: ["slack.com"],
  },
  {
    displayName: "DocuSign",
    category: "business",
    aliases: ["docusign", "docu sign"],
    officialDomains: ["docusign.com"],
  },
  {
    displayName: "DHL",
    category: "shipping",
    aliases: ["dhl"],
    officialDomains: ["dhl.com"],
  },
  {
    displayName: "FedEx",
    category: "shipping",
    aliases: ["fedex", "fed ex"],
    officialDomains: ["fedex.com"],
  },
  {
    displayName: "UPS",
    category: "shipping",
    aliases: ["ups"],
    officialDomains: ["ups.com"],
  },
  {
    displayName: "USPS",
    category: "shipping",
    aliases: ["usps", "united states postal service"],
    officialDomains: ["usps.com"],
  },
  {
    displayName: "Israel Post",
    category: "shipping",
    aliases: ["israelpost", "israel post", "דואר ישראל", "דוארישראל"],
    officialDomains: ["israelpost.co.il"],
  },
  {
    displayName: "חברת החשמל",
    category: "utilities",
    aliases: ["חברת החשמל", "חשמל", "electric", "israel electric", "iec"],
    officialDomains: ["iec.co.il"],
  },
  {
    displayName: "Evri",
    category: "shipping",
    aliases: ["evri", "hermes"],
    officialDomains: ["evri.com"],
  },
  {
    displayName: "Royal Mail",
    category: "shipping",
    aliases: ["royalmail", "royal mail"],
    officialDomains: ["royalmail.com"],
  },
  {
    displayName: "Aramex",
    category: "shipping",
    aliases: ["aramex"],
    officialDomains: ["aramex.com"],
  },
  {
    displayName: "Binance",
    category: "crypto",
    aliases: ["binance"],
    officialDomains: ["binance.com"],
  },
  {
    displayName: "Coinbase",
    category: "crypto",
    aliases: ["coinbase"],
    officialDomains: ["coinbase.com"],
  },
  {
    displayName: "MetaMask",
    category: "crypto",
    aliases: ["metamask", "meta mask"],
    officialDomains: ["metamask.io"],
  },
  {
    displayName: "Trust Wallet",
    category: "crypto",
    aliases: ["trustwallet", "trust wallet"],
    officialDomains: ["trustwallet.com"],
  },
  {
    displayName: "Kraken",
    category: "crypto",
    aliases: ["kraken"],
    officialDomains: ["kraken.com"],
  },
  {
    displayName: "Payoneer",
    category: "payments",
    aliases: ["payoneer"],
    officialDomains: ["payoneer.com"],
  },
  {
    displayName: "Booking.com",
    category: "travel",
    aliases: ["booking", "bookingcom"],
    officialDomains: ["booking.com"],
  },
  {
    displayName: "Airbnb",
    category: "travel",
    aliases: ["airbnb", "air bnb"],
    officialDomains: ["airbnb.com"],
  },
  {
    displayName: "Expedia",
    category: "travel",
    aliases: ["expedia"],
    officialDomains: ["expedia.com"],
  },
  {
    displayName: "Ryanair",
    category: "travel",
    aliases: ["ryanair"],
    officialDomains: ["ryanair.com"],
  },
  {
    displayName: "El Al",
    category: "travel",
    aliases: ["elal", "el al", "אל על"],
    officialDomains: ["elal.com"],
  },
  {
    displayName: "Bituach Leumi",
    category: "government",
    aliases: ["bituachleumi", "btl", "ביטוח לאומי"],
    officialDomains: ["btl.gov.il"],
  },
  {
    displayName: "Mas Hachnasa",
    category: "government",
    aliases: ["tax", "mas", "mashachnasa", "רשות המסים", "מס הכנסה"],
    officialDomains: ["tax.gov.il"],
  },
  {
    displayName: "myGov",
    category: "government",
    aliases: ["mygov", "gov", "govil", "ממשל זמין"],
    officialDomains: ["gov.il"],
  },
  {
    displayName: "National Insurance",
    category: "government",
    aliases: ["nationalinsurance", "socialsecurity"],
    officialDomains: ["ssa.gov"],
  },
];

module.exports = { BRAND_CONFIG };
